config/routes.rb
Rails.application.routes.draw do
  default_url_options host: "localhost:3000"
  namespace :api do
    resources :minors, only: [:show, :index]
    # get 'minors/index'
    # get 'minors/show'
  end

  resources :minors
  get 'welcome/index'
  root 'minors#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
  has_many :faculties
end

app/models/faculty.rb
class Faculty < ApplicationRecord
  has_many :minors
  belongs_to :city
end

app/models/minor.rb
class Minor < ApplicationRecord
  belongs_to :faculty

  def as_json_for_main_page
    {
      title: title,
      kredits: kredits,
      deskription: deskription,
      location: location

    }
  end
end

app/controllers/api/minors_controller.rb
class Api::MinorsController < ApplicationController
  def index
    minors= Minor.all.collect
    minors_data = []

    minors.each do |minor|
      minor_data =  minor.as_json_for_main_page
      minor_data[:url] = api_minor_url(minor)

      minors_data << minor_data
    end

    render json: minors_data
  end

  def show
    minor = Minor.find(params[:id])
    minor_data = minor.as_json_for_main_page
    minor_data[:url] = api_minor_url(minor)

    render json: minor_data
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/minors_controller.rb
class MinorsController < ApplicationController
  before_action :set_minor, only: [:show, :edit, :update, :destroy]

  # GET /minors
  # GET /minors.json
  def index
    @minors = Minor.all
  end

  # GET /minors/1
  # GET /minors/1.json
  def show
  end

  # GET /minors/new
  def new
    @minor = Minor.new
  end

  # GET /minors/1/edit
  def edit
  end

  # POST /minors
  # POST /minors.json
  def create
    @minor = Minor.new(minor_params)

    respond_to do |format|
      if @minor.save
        format.html { redirect_to @minor, notice: 'Minor was successfully created.' }
        format.json { render :show, status: :created, location: @minor }
      else
        format.html { render :new }
        format.json { render json: @minor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /minors/1
  # PATCH/PUT /minors/1.json
  def update
    respond_to do |format|
      if @minor.update(minor_params)
        format.html { redirect_to @minor, notice: 'Minor was successfully updated.' }
        format.json { render :show, status: :ok, location: @minor }
      else
        format.html { render :edit }
        format.json { render json: @minor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /minors/1
  # DELETE /minors/1.json
  def destroy
    @minor.destroy
    respond_to do |format|
      format.html { redirect_to minors_url, notice: 'Minor was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_minor
      @minor = Minor.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def minor_params
      params.require(:minor).permit(:title, :kredits, :deskription, :location)
    end
end

app/controllers/welcome/index_controller.rb
class Welcome::IndexController < ApplicationController
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/api/minors_helper.rb
module Api::MinorsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/minors_helper.rb
module MinorsHelper
end

app/helpers/welcome/index_helper.rb
module Welcome::IndexHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Project3Mod</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/minors/_form.html.erb
<%= form_with(model: minor, local: true) do |form| %>
  <% if minor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(minor.errors.count, "error") %> prohibited this minor from being saved:</h2>

      <ul>
        <% minor.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :kredits %>
    <%= form.number_field :kredits %>
  </div>

  <div class="field">
    <%= form.label :deskription %>
    <%= form.text_area :deskription %>
  </div>

  <div class="field">
    <%= form.label :location %>
    <%= form.text_field :location %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/minors/edit.html.erb
<h1>Editing Minor</h1>

<%= render 'form', minor: @minor %>

<%= link_to 'Show', @minor %> |
<%= link_to 'Back', minors_path %>

app/views/minors/index.html.erb
<% City.all.each do |city| %>
  <h2><%= city.name %></h2>
  <ul>
    <% city.faculties.each do |faculty| %>
      <h3><%= faculty.name %></h3>
      <% faculty.minors.each do |minor| %>
        <p><%= minor.title %></p>
      <% end %>
    <% end %>
  </ul>
<% end %>

app/views/minors/new.html.erb
<h1>New Minor</h1>

<%= render 'form', minor: @minor %>

<%= link_to 'Back', minors_path %>

app/views/minors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @minor.title %>
</p>

<p>
  <strong>Kredits:</strong>
  <%= @minor.kredits %>
</p>

<p>
  <strong>Deskription:</strong>
  <%= @minor.deskription %>
</p>

<p>
  <strong>Location:</strong>
  <%= @minor.location %>
</p>

<%= link_to 'Edit', edit_minor_path(@minor) %> |
<%= link_to 'Back', minors_path %>

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>

<script type="text/javascript">
  fetch('http://localhost:3000/api/minors')
  .then(response => response.json())
  .then(data => {
    let div = document.createElement('div')
    div.innerHTML = JSON.stringify(data)
    console.log(data)
    document.body.append(div)
  })
</script>